version: '3.5'
services:
  iredmail:
    image: iredmail/mariadb:stable
    restart: unless-stopped
    container_name: ${DOCKER_PROJECT_NAME}_iredmail
    hostname: ${IREDMAIL_HOSTNAME}
    domainname: ${IREDMAIL_DOMAIN}
    networks:
      eztnet:
        ipv4_address: 172.21.0.2
    environment:
      - DOMAIN=${IREDMAIL_DOMAIN}
      - HOSTNAME=${IREDMAIL_HOSTNAME}
      - FIRST_MAIL_DOMAIN=${IREDMAIL_FIRST_MAIL_DOMAIN}
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=${IREDMAIL_FIRST_MAIL_DOMAIN_ADMIN_PASSWORD}
      - MLMMJADMIN_API_TOKEN=${IREDMAIL_MLMMJADMIN_API_TOKEN}
      - ROUNDCUBE_DES_KEY=${IREDMAIL_ROUNDCUBE_DES_KEY}
      - MYSQL_ROOT_PASSWORD=${IREDMAIL_MYSQL_ROOT_PASSWORD}
      - TIMEZONE=${IREDMAIL_TIMEZONE}
      - POSTMASTER_PASSWORD=${IREDMAIL_POSTMASTER_PASSWORD}
      - IREDAPD_PLUGINS=${IREDMAIL_IREDAPD_PLUGINS}
      - SOGO_WORKERS=1
      # - MAIL_THE_TIP_FILE=NO
    volumes:
      - ./docker/iredmail/data/backup-mysql:/var/vmail/backup/mysql
      - ./docker/iredmail/data/mailboxes:/var/vmail/vmail1
      - ./docker/iredmail/data/mlmmj:/var/vmail/mlmmj
      - ./docker/iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive
      - ./docker/iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy
      - ./docker/iredmail/data/custom:/opt/iredmail/custom
      - ./docker/iredmail/data/ssl:/opt/iredmail/ssl
      - ./docker/iredmail/data/mysql:/var/lib/mysql
      - ./docker/iredmail/data/clamav:/var/lib/clamav
      - ./docker/iredmail/data/sa_rules:/var/lib/spamassassin
      - ./docker/iredmail/data/postfix_queue:/var/spool/postfix
    ports:
      - ${IREDMAIL_HTTP_PORT}:80         # HTTP_PORT
      - ${IREDMAIL_TCP_PORT}:443         # TCP_PORT
      - 25:25                            # SMTP
      - 587:587                          # Submission
      - 110:110                          # Unencrypted POP3
      - 143:143                          # Unencrypted IMAP
      - 993:993                          # Encrypted IMAP
      - 995:995                          # Encrypted POP3

networks:
  eztnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
